### ISSUE TITLE
Apresentação dos membros do projeto

### ISSUE THREAD

**Issue by PauloHartwig** [LordFabricio/RoboCode#1]
Esta issue é para todos membros do projeto se apresentarem e principalmente colocarem seus dados para contato.

**Comment by PauloHartwig** [comment]
Eae pessoal!
Estarei fazendo parte deste projeto como engenheiro.

Contato:
- Facebook: https://www.facebook.com/paulohhartwig
- Email: paulohhartwig@gmail.com
- Discord: Paulo H. #9341

Estou com meu e-mail aberto praticamente o dia inteiro, então qualquer coisa só chamar.

**Comment by LordFabricio** [comment]
Opa!!! Blz
Esto Aqui para colaborar

- E-Mail: ftlord@gmail.com
- Discord: LordFabricio #6899
- FaceBook: https://www.facebook.com/fabricio.mota.108

Qualquer coisa prende o grito

**Comment by eduardoxRib** [comment]
Opa, fazendo parte no projeto como coder!
 e-mail: eduardoxrib@gmail.com
 Facebook: https://www.facebook.com/eduardoxlord

 Qualquer coisa estão aí os contatos

**Comment by igormjq** [comment]
Perdão a demora, pois estou em correria com o TCC.
Sou Igor Marini Jaekel Quevedo, aluno do 5º semestre do curso de Análise e Desenvolvimento de Sistemas.

Contato:
Email igormjq@gmail.com
Facebook https://www.facebook.com/igormjq
