### ISSUE TITLE
Nome dos Robos

### ISSUE THREAD

**Issue by PauloHartwig** [LordFabricio/RoboCode#2]
Esta issue é para planejar um nome para dar ao seu tanque robô.

**Comment by LordFabricio** [comment]
Se for selecionado o Tropas de Elite tem que ser:

Capitão Nascimento.
Aspirante Mathias.
Zero Dois.

**Comment by eduardoxRib** [comment]
Robo1: Gavião ou ClintBarton (Arqueiro por se mexer pouco e focar em mirar)
 Robo2: HulkãoEsmaga (issue do Robo2)
 Robo3: ?

**Comment by PauloHartwig** [comment]
@eduardoxRib 
O terceiro poderia ser o Mercúrio, e a gente faz ele se movimentar bastante.

**Comment by LordFabricio** [comment]
Blz!!!

Na reunião de Quarta definimos o nome dos Robos:

- G2M_GaviaoArqueiro
- G2M_HulkaoEsmaga
- G2M_Mercurio
