### ISSUE TITLE
Pesquisar Materiais

### ISSUE THREAD

**Issue by PauloHartwig** [LordFabricio/RoboCode#3]
Nesta issue reuniremos links que podem ser uteis de alguma maneira na construção dos robôs e no desenvolvimento projeto.

**Links já disponibilizados pelo professor:**

Links Interessantes
- https://www.ft.unicamp.br/liag/robocode/robocode/por-onde-comecar/
- https://www.ft.unicamp.br/liag/wp-content/uploads/2016/03/Robocode.pdf

RoboCode no NetBeans
- http://robowiki.net/wiki/Robocode/NetBeans/Configure
- https://wiki.portugal-a-programar.pt/dev_geral:java:robocode:netbeans

Documentação
- http://robocode.sourceforge.net/
- http://robowiki.net/wiki/Main_Page

**Comment by PauloHartwig** [comment]
Link da descrição do trabalho, pra ninguém se perder.
- https://docs.google.com/document/d/1eN6IITL11Bn0KGR8ESm4x9XrpYvh4tsQyA6Y86Dx40k/edit

**Comment by LordFabricio** [comment]
Achei este também

- http://www.ufjf.br/jairo_souza/files/2015/11/Robocode-Manual-de-Instruc%CC%A7o%CC%83es.pdf

**Comment by PauloHartwig** [comment]
Esse PDF do @LordFabricio tem explicações muito boas de vários métodos.

**Comment by PauloHartwig** [comment]
Aqui neste site tem um mini-curso bem completo sobre robocode. Totalmente em PT-BR
- http://www.robocodebrasil.com.br/mini-curso.php

**Comment by LordFabricio** [comment]
Massa nesse link do Mini-Curso que o PauloHartwig da para entender como funciona o robo.

**Comment by PauloHartwig** [comment]
Achei legal esse trecho onde explica um pouco a funcionalidade do Scanner.

**Ele pega o angulo que o cara tava em relação ao nosso robô e gira o canhão desse robô para aquele angulo e atira.**

Acho que a gente pode seguir essa mesma linha de pensamento.

Esta na página 24 do PDF que o Fabricio achou.

![funcao do scanner](https://user-images.githubusercontent.com/20866576/41372309-4c6299e0-6f23-11e8-9502-fa9bc7671e46.PNG)

**Comment by PauloHartwig** [comment]
Nesse link, tem algumas informações de como criar alguns métodos.
https://felipepriuli.wordpress.com/2010/11/09/robocode-priulidestroyer/

Informações:
- Como funciona a energia
- Quando o scanner é ativado
- Qual o método que é ativado quando tu bate na parede
- Qual o método que é ativado quando tu leva um tiro

**Comment by LordFabricio** [comment]
Achei um material da IBM sobre Robocode.

- https://www.ibm.com/developerworks/library/j-robotips/index.html

Vale a pena dar uma olhada, eles tem até um robo la pra download.
