### ISSUE TITLE
Dúvidas / Dificuldades

### ISSUE THREAD

**Issue by PauloHartwig** [LordFabricio/RoboCode#4]
O propósito desta issue, é que os **programadores** (1° semestre) coloquem alguma dúvida/dificuldade que estão tendo e os **engenheiros** (3° semestre) tentem ajudar a encontrar uma solução interagindo pelo chat da própria issue ou outros meios.

**Comment by eduardoxRib** [comment]
Problemas ao trabalhar em uma nova versão do robo1, não consigo encontrar o método certo para apontar o canhão para o inimigo, usando o método:
*
public void onScannedRobot(ScannedRobotEvent e) {
	double angulo = e.getBearing();
	System.out.println(e.getBearing());
	turnGunRight(angulo);
*
 Ele não leva em conta o ângulo em que o canhão estava, acaba que vai para direita em relação ao ângulo, e não se ajusta exatamente.
 Busquei formas de usar a função que alguns robôs do simple usam para mirar o canhão como:
*
gunTurnAmt = normalRelativeAngleDegrees(e.getBearing() + (getHeading() - getRadarHeading()));
turnGunRight(gunTurnAmt);
*
(Robo: Simple.Tracker) ^^^^ 
 Mas deu problemas não reconhecendo o "normalRelativeAngleDegress" mesmo puxando a biblioteca Robocode.Util.normalRelativeAngleDegrees; 
 Enfim, estou buscando formas de melhorar a precisão do robo... Qualquer ajuda agradeço

**Comment by PauloHartwig** [comment]
No meu PC reconheceu!!
Tentei fazer como este artigo aqui:
https://wiki.portugal-a-programar.pt/dev_geral:java:robocode:manteremmira

É um artigo ensinando a manter a mira no robô adversário (mas não atirar) e deu certo.

**Comment by PauloHartwig** [comment]
Mas no caso eu dei extends na classe **AdvancedRobot**, tem que cuidar se é a mesma que tu ta usando, quem sabe é diferente.

**Comment by eduardoxRib** [comment]
Ok vou implementar esse método hoje, e implementar comentários pelo código
como o pedido do trabalho! Previsão para robo2?

Em seg, 18 de jun de 2018 09:18, Paulo H. Hartwig Jr. <
notifications@github.com> escreveu:

**Comment by PauloHartwig** [comment]
Vou tentar bolar alguma ideia de estratégia hoje.
