### ISSUE TITLE
Cores da Equipe

### ISSUE THREAD

**Issue by PauloHartwig** [LordFabricio/RoboCode#5]
Nesta issue, definiremos a(s) cor(es), para padronizar o "uniforme" da equipe.
Indiquem sugestões.

**Comment by LordFabricio** [comment]
Acredito que podemos usar os personagens da tropa de elite.

Cor do Corpo - Preto
Cor do Canhão - Preto
Cor do Radar - Branco

**Comment by PauloHartwig** [comment]
Ai temos que ver com o Angelo pra ver se ele deixa usar Tropa de Elite ao invés de Marvel.

**Comment by PauloHartwig** [comment]
Meu palpite: Tudo vermelho

**Comment by PauloHartwig** [comment]
Ficou decidido que o "uniforme" da equipe irá ser:
- Corpo: Vermelho
- Canhão: Vermelho
- Radar: Preto
