### ISSUE TITLE
Personagens Inspirados

### ISSUE THREAD

**Issue by PauloHartwig** [LordFabricio/RoboCode#6]
No trabalho consta que os robôs deverão ser inspirados em personagens da Marvel.
Esta issue serve para discutirmos quais os 3 personagens que serão escolhidos.
- Indiquem alguns personagens (prioridade)
- Como o robô se pareceria com esse personagem

**Comment by LordFabricio** [comment]
Vamos nos Inspirar em:

Tropas de Elite - Heróis Nacionais. 

Para com essa de Herói Americano.

**Comment by PauloHartwig** [comment]
No fim, os heróis decididos foram:
- Gavião Arqueiro
- Hulk
- Mercúrio
