### ISSUE TITLE
Robôs Adversários

### ISSUE THREAD

**Issue by PauloHartwig** [LordFabricio/RoboCode#8]
Para as partidas qualificatórias todas os grupos terão que enfrentar 3 robôs já prontos em uma partida de 10 rounds.

**Robos:**
- sample.Walls
- sample.Tracker
- sample.SpinBot.

Nesta issue vamos reunir informações sobre como é o comportamento destes robôs.
- Coloquem links ou informações que conseguirem deles
- Precisamos mudar de estratégia?

**Comment by eduardoxRib** [comment]
Nosso robo1 está dando conta do Tracker, e aleatoriamente ganhando ou perdendo do SpinBot. Mas dentre os três, Walls tem um movimento contínuo em volta do campo, fez Robo1 perder todas com eles por errar os tiros e ir perdendo energia. Algum dos nossos robôs deve estar qualificado para derrotar um adversário do tipo dele.

**Comment by PauloHartwig** [comment]
**SpinBot**
- Fica andando em círculos independente de qualquer ação
- Atira onde ele localizou um robô adversário sem parar de se mover

**Comment by PauloHartwig** [comment]
**Tracker**
- Anda até chegar perto de onde ele localizou um robô
- Segue o inimigo sem atirar
- Só atira quando chegar perto, antes não
- Atira um tiro mais forte
- Fazendo isso ele fica recuperando muita vida caso ele acerte

**Comment by PauloHartwig** [comment]
**Walls**
- Fica andando pelas paredes
- Localiza o robô adversário enquanto gira
- Atira um tiro forte
- Essa movimentação é bem previsível
- Todos os tiros que forem retos e de longe acertam porque ele sempre volta para aquele lugar
